### ISSUE TITLE
Server Crashed. UTIL_StringToLower

### ISSUE THREAD

**Issue by neygomon** [Arkshine/AdminFreeLook#5]
![screen1](https://cloud.githubusercontent.com/assets/7746583/5815426/feb065ba-a0ae-11e4-9215-7b7c8ca072ab.png)
![screen2](https://cloud.githubusercontent.com/assets/7746583/5815427/fefbdda6-a0ae-11e4-8301-71d74e35705b.png)

Hello.
AdminFreeLook 1.5.4 installed and the server began to fall.
In debug.log swears on module cstrike.
Build Server 6153 beta
Amxmodx 1.8.3 git4530

With version AdminFreeLook 1.5.3 no problems.

Debug.log file attached.
I hope to fix it;)

Sorry for my English. I use google translate

**Comment by Arkshine** [comment]
I'm not sure what happens.

`UTIL_StringToLower` is used only by `cstrike` module here:

```PAWN
DETOUR_DECL_STATIC1(C_ClientCommand, void, edict_t*, pEdict) // void ClientCommand(edict_t *pEntity)
{
	const char *command = CMD_ARGV(0);
	
	// A new command is triggered, reset variable, always.
	CurrentItemId = 0;

	// Purpose is to retrieve an item id based on alias name or selected item from menu,
	// to be used in OnBuy* forwards.
	if ((ForwardOnBuyAttempt != -1 || ForwardOnBuy != -1) && command && *command)
	{
		// Just for safety.
		command = UTIL_StringToLower((char *)command);
...
```
I don't see how it can crash even though `command` is well checked before. Maybe for some reason it contains garbage.

Anyway, `AdminFreeLook` module doesn't do anything related to `ClientCommand`: it doesn't send commands, nor it hooks such function. So I'm not sure how this crash could be related to this module.

Are you absolutely  sure it's because of this module?
Tell me the context of the crash, how to reproduce it ? etc.

**Comment by neygomon** [comment]
I just filled AdminFreeLook 1.5.4 and rebooted the server.
And the server began to fall steadily.
Thought that the case in version amxmodx, upgrade to the latest GIT.
Server worked a little longer, and still fell, swearing cstrike.
Then I rolled up to version 1.5.3 freelook all. No problem. The server is stable.

**Comment by Arkshine** [comment]
Check git4532+ ; I've removed `UTIL_StringToLower` from `cstrike` module. It was pointless and dangerous code as it is.

**Comment by neygomon** [comment]
Thanks, I'll try.
About the results are reported

**Comment by neygomon** [comment]
Everything works well.
Thank U!
Sorry if off topic.
